http.listener.host: "0.0.0.0"
http.listener.port: "8081"
http.listener.readtimeout: "30000"


smtp.host: "smtp.gmail.com"
smtp.port: "587"
smtp.user: "htyagi3636@gmail.com"
smtp.password: "dimx frhg tyey pbxv"